apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: cineai
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/cineai
  MINIO_URL: http://minio-service:9000
  MINIO_BUCKET: movies
  OLLAMA_URL: http://ollama-service:11434
  OLLAMA_MODEL: llama3.2
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: cineai
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cineai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: backend
          image: ghcr.io/kavyad-bytes/cineai-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: cineai
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: cineai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70