apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cineai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: frontend
          image: ghcr.io/kavyad-bytes/cineai-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: cineai
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80